name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v
        working-directory: test